### ISSUE TITLE
Fatal error with ep_post_sync_kill filter in 3.0

### ISSUE THREAD

**Issue by aaemnnosttv** [10up/ElasticPress#1351]
__Have you searched for similar issues before submitting this one?__
Yes

__Is this a bug, question or feature request?__
~~undocumented backwards compatibility change~~ this is documented in the changelog for v3.
I would say this is a bug as it is a simple (yet serious) error to mitigate.

__Describe the issue you encountered:__
After upgrading to v3, I get a fatal error from a callback for the `ep_post_sync_kill` filter. In v2, it provided 3 arguments to the callback, which my callback is expecting, and in v3 it only passes 2.

v2
https://github.com/10up/ElasticPress/blob/ca929db2869576b5e1975436eda4d21f150e50b3/classes/class-ep-sync-manager.php#L268

v3
https://github.com/10up/ElasticPress/blob/b3d96a72dd54db1def357d6c0f093a2a182b6e06/includes/classes/Indexable/Post/SyncManager.php#L161

__Current WordPress version?__
5.2.1

__Current ElasticPress version?__
3.0.2

### Error

```
Too few arguments to function ...(), 2 passed in /var/www/html/wp-includes/class-wp-hook.php on line 286 and exactly 3 expected
```

**Comment by aaemnnosttv** [comment]
I see now that this change is in the changelog for v3.

Perhaps a `$post_id` should be passed twice for semi-backwards compatibility? At least to not fatal error here?
